fix: run migrations even if DB creation failed (#7)
* fix: try running migrations even if DB creation failed

* docs: use ROBSERVER_PG_ADDR in documentation instead of DATABASE_URL

diff --git a/scripts/sqlx-create-run b/scripts/sqlx-create-run
--- a/scripts/sqlx-create-run
+++ b/scripts/sqlx-create-run
@@ -1,4 +1,6 @@
 #!/usr/bin/env bash
 
-cargo sqlx database create || exit 1
-cargo sqlx migrate run
+echo "Applying migrations"
+
+cargo sqlx database create --database-url "${ROBSERVER_PG_ADDR}" && echo "DB created" || echo "DB creation failed"
+cargo sqlx migrate run --database-url "${ROBSERVER_PG_ADDR}"
